# Generated by Django 3.1.1 on 2020-09-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name="taskinfo",
            order_with_respect_to="task",
        ),
    ]
