# Generated by Django 3.1.1 on 2020-09-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_auto_20200930_1532"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskinfo",
            options={"ordering": ("-pk",)},
        ),
        migrations.AlterField(
            model_name="taskinfo",
            name="dead_line",
            field=models.DateField(
                blank=True, null=True, verbose_name="Estimated deadline"
            ),
        ),
        migrations.AlterField(
            model_name="taskinfo",
            name="status",
            field=models.CharField(
                choices=[
                    ("n", "New"),
                    ("p", "Planned"),
                    ("w", "In work"),
                    ("d", "Done"),
                ],
                default="n",
                max_length=1,
                verbose_name="Status",
            ),
        ),
        migrations.AlterOrderWithRespectTo(
            name="taskinfo",
            order_with_respect_to=None,
        ),
    ]
