# Generated by Django 3.1.1 on 2020-10-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_auto_20201001_1641"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskinfo",
            name="actual",
            field=models.BooleanField(default=True),
        ),
    ]
